// parsing comments

var syntax = require(".."),
    assert = require("assert"),
    common = require("./common"),
    testCompile = common.testKCompile,
    testDir = common.testDir;

var ibem = require('fs')
      .readFileSync(
        __dirname + '/../bower_components/bem-core/common.blocks/i-bem/i-bem.bemhtml',
        'utf8'),
    compat = require("bemhtml-compat"),
    esprima = require("esprima"),
    esgen = require("escodegen").generate,
    path = require("path"),
    fs = require("fs");

var pp = require("zeHelpers").prettyPrint;

var dir = path.dirname(module.filename),
    utf8 = { encoding:'utf8' },
    getSource = function (file) {
      return fs.readFileSync(path.join(dir, file), utf8);
    },
    testParse = function (file, result) {
      var source = getSource(file);
      common.testKParse(source, result);
    };

describe('Meta info', function() {

  describe('Parser', function () {

    it('should parse mixed js and templates', function () {
      testParse('./kparser/ext-js.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'funcStmt',
                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                      [ 'name', 'outside' ],
                      [ 'spacesAndComments', [] ],
                      [ 'commaList',
                        [ 'funcArg',
                          [ 'spacesAndComments', [] ],
                          [ 'name', 'a' ],
                          [ 'spacesAndComments', [] ] ],
                        [ 'funcArg',
                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                          [ 'name', 'b' ],
                          [ 'spacesAndComments', [] ] ] ],
                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                      [ 'blockStmt',
                        [ 'stmts',
                          [ 'stmt',
                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                            [ 'returnStmt',
                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                              [ 'string', '\'', [ 'h', 'e', 'l', 'l', 'o' ] ],
                              [ 'spacesAndComments', [] ] ],
                            [ 'stmtEnd', [ 'spacesAndComments', [] ], ';' ],
                            [ 'spacesAndComments', [] ] ] ] ] ],
                    [ 'stmtEnd' ],
                    [ 'spacesAndComments', [] ] ],
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'emptyStmt' ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ], '\n' ],
                    [ 'spacesAndComments', [ [ 'spaces', '\n' ] ] ] ],
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'b1' ] ],
                                [ 'spacesAndComments', [] ] ] ] ],
                          [ 'pred',
                            [ 'stdMode',
                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                              [ 'name', 'content' ],
                              [ 'spacesAndComments', [] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'body',
                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                          [ 'literalBody', [ 'string', '\'', [ 'b', 'l', 'a' ] ] ],
                          [ 'spacesAndComments', [] ] ],
                        [ 'spacesAndComments', [] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ])
    })

    it('should parse multiple templates', function () {
      testParse('basic/info6.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'b-wrapper' ] ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'templateBlock',
                          [ [ 'sub',
                              [ [ 'spacesAndComments', [ [ 'spaces', '\n    ' ] ] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'tag' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'literalBody', [ 'string', '\'', [ 'w', 'r', 'a', 'p' ] ] ],
                                  [ 'spacesAndComments', [ [ 'spaces', '    ' ] ] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'sub',
                              [ [ 'spacesAndComments', [] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'content' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'generalBody',
                                    [ 'stmt',
                                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                      [ 'returnStmt',
                                        [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                        [ 'getExprDot',
                                          [ 'getExprDot',
                                            [ 'keyword', 'this' ],
                                            [ 'spacesAndComments', [] ],
                                            [ 'spacesAndComments', [] ],
                                            [ 'name', 'ctx' ] ],
                                          [ 'spacesAndComments', [] ],
                                          [ 'spacesAndComments', [] ],
                                          [ 'name', 'content' ] ],
                                        [ 'spacesAndComments', [] ] ],
                                      [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                                      [ 'spacesAndComments', [] ] ] ],
                                  [ 'spacesAndComments', [] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'spacesAndComments', [] ] ] ],
                        [ 'spacesAndComments', [ [ 'spaces', '\n\n' ] ] ] ] ],
                    [ 'stmtEnd' ],
                    [ 'spacesAndComments', [] ] ],
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'b-inner' ] ],
                                [ 'spacesAndComments', [] ] ] ] ],
                          [ 'pred',
                            [ 'stdMode',
                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                              [ 'name', 'def' ],
                              [ 'spacesAndComments', [] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'body',
                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                          [ 'generalBody',
                            [ 'stmt',
                              [ 'spacesAndComments', [] ],
                              [ 'exprStmt',
                                [ 'applyCtx',
                                  [ 'spacesAndComments', [] ],
                                  [ 'commaList',
                                    [ 'arg',
                                      [ 'spacesAndComments', [] ],
                                      [ 'obj',
                                        [ 'commaList',
                                          [ 'objItem',
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'name', 'block' ],
                                            [ 'spacesAndComments', [] ],
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'string',
                                              '\'',
                                              [ 'b', '-', 'w', 'r', 'a', 'p', 'p', 'e', 'r' ] ],
                                            [ 'spacesAndComments', [] ] ],
                                          [ 'objItem',
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'name', 'content' ],
                                            [ 'spacesAndComments', [] ],
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'getExprDot',
                                              [ 'getExprDot',
                                                [ 'keyword', 'this' ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'name', 'ctx' ] ],
                                              [ 'spacesAndComments', [] ],
                                              [ 'spacesAndComments', [] ],
                                              [ 'name', 'content' ] ],
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ],
                                      [ 'spacesAndComments', [] ] ] ],
                                  [ 'spacesAndComments', [ [ 'spaces', '\n' ] ] ] ] ],
                              [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                              [ 'spacesAndComments', [] ] ] ],
                          [ 'spacesAndComments', [] ] ],
                        [ 'spacesAndComments', [] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ]);
    });

    it('should parse deeply nested template', function() {
      testParse('./basic/info7.bemhtml',
           [ 'stmts',
             [ 'stmt',
               [ 'spacesAndComments', [] ],
               [ 'template',
                 [ [ 'spacesAndComments', [] ],
                   [ 'predicates',
                     [ 'pred',
                       [ 'block',
                         [ [ 'spacesAndComments', [] ],
                           [ 'name', 'block' ],
                           [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                           [ 'value', [ 'string', 'b-link' ] ],
                           [ 'spacesAndComments', [] ] ] ] ],
                     [ 'pred',
                       [ 'elem',
                         [ [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                           [ 'name', 'elem' ],
                           [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                           [ 'value', [ 'string', 'e1' ] ],
                           [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                   [ 'spacesAndComments', [] ],
                   [ 'templateBlock',
                     [ [ 'sub',
                         [ [ 'spacesAndComments', [ [ 'spaces', '\n  ' ] ] ],
                           [ 'predicates',
                             [ 'pred',
                               [ 'stdMode',
                                 [ 'spacesAndComments', [] ],
                                 [ 'name', 'tag' ],
                                 [ 'spacesAndComments', [] ] ] ] ],
                           [ 'spacesAndComments', [] ],
                           [ 'body',
                             [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                             [ 'literalBody', [ 'string', '\'', [ 's', 'p', 'a', 'n' ] ] ],
                             [ 'spacesAndComments', [ [ 'spaces', '  ' ] ] ] ],
                           [ 'spacesAndComments', [] ] ] ],
                       [ 'sub',
                         [ [ 'spacesAndComments', [] ],
                           [ 'predicates',
                             [ 'pred',
                               [ 'custom',
                                 [ 'spacesAndComments', [] ],
                                 [ 'getExprDot',
                                   [ 'getExprDot',
                                     [ 'keyword', 'this' ],
                                     [ 'spacesAndComments', [] ],
                                     [ 'spacesAndComments', [] ],
                                     [ 'name', 'ctx' ] ],
                                   [ 'spacesAndComments', [] ],
                                   [ 'spacesAndComments', [] ],
                                   [ 'name', 'url' ] ],
                                 [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ],
                           [ 'spacesAndComments', [] ],
                           [ 'templateBlock',
                             [ [ 'sub',
                                 [ [ 'spacesAndComments', [ [ 'spaces', '\n     ' ] ] ],
                                   [ 'predicates',
                                     [ 'pred',
                                       [ 'stdMode',
                                         [ 'spacesAndComments', [] ],
                                         [ 'name', 'tag' ],
                                         [ 'spacesAndComments', [] ] ] ] ],
                                   [ 'spacesAndComments', [] ],
                                   [ 'body',
                                     [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                     [ 'literalBody', [ 'string', '\'', [ 'a' ] ] ],
                                     [ 'spacesAndComments', [ [ 'spaces', '     ' ] ] ] ],
                                   [ 'spacesAndComments', [] ] ] ],
                               [ 'sub',
                                 [ [ 'spacesAndComments', [] ],
                                   [ 'predicates',
                                     [ 'pred',
                                       [ 'stdMode',
                                         [ 'spacesAndComments', [] ],
                                         [ 'name', 'attrs' ],
                                         [ 'spacesAndComments', [] ] ] ] ],
                                   [ 'spacesAndComments', [] ],
                                   [ 'body',
                                     [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                     [ 'generalBody',
                                       [ 'stmt',
                                         [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                         [ 'returnStmt',
                                           [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                           [ 'obj',
                                             [ 'commaList',
                                               [ 'objItem',
                                                 [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                 [ 'name', 'href' ],
                                                 [ 'spacesAndComments', [] ],
                                                 [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                 [ 'getExprDot',
                                                   [ 'getExprDot',
                                                     [ 'keyword', 'this' ],
                                                     [ 'spacesAndComments', [] ],
                                                     [ 'spacesAndComments', [] ],
                                                     [ 'name', 'ctx' ] ],
                                                   [ 'spacesAndComments', [] ],
                                                   [ 'spacesAndComments', [] ],
                                                   [ 'name', 'url' ] ],
                                                 [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ],
                                           [ 'spacesAndComments', [] ] ],
                                         [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                                         [ 'spacesAndComments', [] ] ] ],
                                     [ 'spacesAndComments', [ [ 'spaces', '     ' ] ] ] ],
                                   [ 'spacesAndComments', [] ] ] ],
                               [ 'sub',
                                 [ [ 'spacesAndComments', [] ],
                                   [ 'predicates',
                                     [ 'pred',
                                       [ 'customMode',
                                         [ 'spacesAndComments', [] ],
                                         [ 'name', 'reset' ],
                                         [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ],
                                   [ 'spacesAndComments', [] ],
                                   [ 'templateBlock',
                                     [ [ 'sub',
                                         [ [ 'spacesAndComments', [ [ 'spaces', '\n         ' ] ] ],
                                           [ 'predicates',
                                             [ 'pred',
                                               [ 'stdMode',
                                                 [ 'spacesAndComments', [] ],
                                                 [ 'name', 'attrs' ],
                                                 [ 'spacesAndComments', [] ] ] ] ],
                                           [ 'spacesAndComments', [] ],
                                           [ 'body',
                                             [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                             [ 'literalBody',
                                               [ 'obj',
                                                 [ 'commaList',
                                                   [ 'objItem',
                                                     [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                     [ 'name', 'href' ],
                                                     [ 'spacesAndComments', [] ],
                                                     [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                     [ 'name', 'undefined' ],
                                                     [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                                             [ 'spacesAndComments', [ [ 'spaces', '      ' ] ] ] ],
                                           [ 'spacesAndComments', [] ] ] ],
                                       [ 'spacesAndComments', [] ] ] ],
                                   [ 'spacesAndComments', [] ] ] ],
                               [ 'spacesAndComments', [ [ 'spaces', '\n   ' ] ] ] ] ],
                           [ 'spacesAndComments', [] ] ] ],
                       [ 'spacesAndComments', [ [ 'spaces', '\n' ] ] ] ] ],
                   [ 'spacesAndComments', [] ] ] ],
               [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
               [ 'spacesAndComments', [] ] ] ]);
    });

    it('should parse applyCtx expr', function () {
      testParse('./kparser/general-body-apply-expr.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'b-inner' ] ],
                                [ 'spacesAndComments', [] ] ] ] ],
                          [ 'pred',
                            [ 'stdMode',
                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                              [ 'name', 'def' ],
                              [ 'spacesAndComments', [] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'body',
                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                          [ 'generalBody',
                            [ 'stmt',
                              [ 'spacesAndComments', [] ],
                              [ 'exprStmt',
                                [ 'bracketedExpr',
                                  [ 'spacesAndComments', [] ],
                                  [ 'binop',
                                    [ 'applyCtx',
                                      [ 'spacesAndComments', [] ],
                                      [ 'commaList',
                                        [ 'arg',
                                          [ 'spacesAndComments', [] ],
                                          [ 'obj',
                                            [ 'commaList',
                                              [ 'objItem',
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                [ 'name', 'block' ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                [ 'string',
                                                  '\'',
                                                  [ 'b', '-', 'w', 'r', 'a', 'p', 'p', 'e', 'r' ] ],
                                                [ 'spacesAndComments', [] ] ],
                                              [ 'objItem',
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                [ 'name', 'content' ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                [ 'getExprDot',
                                                  [ 'getExprDot',
                                                    [ 'keyword', 'this' ],
                                                    [ 'spacesAndComments', [] ],
                                                    [ 'spacesAndComments', [] ],
                                                    [ 'name', 'ctx' ] ],
                                                  [ 'spacesAndComments', [] ],
                                                  [ 'spacesAndComments', [] ],
                                                  [ 'name', 'content' ] ],
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ],
                                          [ 'spacesAndComments', [] ] ] ],
                                      [ 'spacesAndComments', [] ] ],
                                    [ 'op',
                                      [ 'spacesAndComments', [] ],
                                      ',',
                                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ],
                                    [ 'number', '42' ] ],
                                  [ 'spacesAndComments', [] ] ] ],
                              [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                              [ 'spacesAndComments', [] ] ] ],
                          [ 'spacesAndComments', [] ] ],
                        [ 'spacesAndComments', [] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ])
    });

    it('should parse whole-line comments', function() {
      testParse('./basic/info1.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments',
                      [ [ 'comment', '// comment here' ], [ 'spaces', '\n' ] ] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'logo' ] ],
                                [ 'spacesAndComments', [] ] ] ] ],
                          [ 'pred',
                            [ 'stdMode',
                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                              [ 'name', 'tag' ],
                              [ 'spacesAndComments', [] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'body',
                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                          [ 'literalBody', [ 'string', '\'', [ 'i', 'm', 'g' ] ] ],
                          [ 'spacesAndComments', [] ] ],
                        [ 'spacesAndComments', [] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ]
               );
    });

    it('should parse end-of-line comments', function() {
      testParse('./basic/info2.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'logo' ] ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'templateBlock',
                          [ [ 'sub',
                              [ [ 'spacesAndComments', [ [ 'spaces', '\n  ' ] ] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'tag' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'literalBody', [ 'string', '\'', [ 'i', 'm', 'g' ] ] ],
                                  [ 'spacesAndComments',
                                    [ [ 'spaces', '                                ' ],
                                      [ 'comment', '// end of line comment' ] ] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'sub',
                              [ [ 'spacesAndComments', [ [ 'spaces', '\n  ' ] ] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'attrs' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'literalBody',
                                    [ 'bracketedExpr',
                                      [ 'spacesAndComments', [] ],
                                      [ 'obj',
                                        [ 'commaList',
                                          [ 'objItem',
                                            [ 'spacesAndComments', [] ],
                                            [ 'name', 'alt' ],
                                            [ 'spacesAndComments', [] ],
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'string', '\'', [ 'l', 'o', 'g', 'o' ] ],
                                            [ 'spacesAndComments', [] ] ],
                                          [ 'objItem',
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'name', 'href' ],
                                            [ 'spacesAndComments', [] ],
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'string',
                                              '\'',
                                              [ 'h', 't', 't', 'p', ':', '/', '/', '.', '.', '.' ] ],
                                            [ 'spacesAndComments', [] ] ] ] ],
                                      [ 'spacesAndComments', [] ] ] ],
                                  [ 'spacesAndComments', [ [ 'comment', '// another comment' ] ] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'spacesAndComments', [ [ 'spaces', '\n' ] ] ] ] ],
                        [ 'spacesAndComments', [] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ]
               );
    });

    it('should parse multi-line comments', function() {
      testParse('./basic/info5.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments',
                      [ [ 'comment',
                          '/*\n *\n  long winded comment here with code inside\n\n  block(\'logo\')(\n  tag()(\'img\'),\n  attrs()({alt: \'logo\', href: \'http://...\'})\n  )\n *\n*/' ],
                        [ 'spaces', '\n\n' ] ] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'b-bla' ] ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'templateBlock',
                          [ [ 'sub',
                              [ [ 'spacesAndComments', [ [ 'spaces', '\n  ' ] ] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'tag' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [] ],
                                  [ 'literalBody', [ 'string', '\'', [ 's', 'p', 'a', 'n' ] ] ],
                                  [ 'spacesAndComments', [ [ 'spaces', '  ' ] ] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'sub',
                              [ [ 'spacesAndComments', [] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'mod',
                                      [ [ 'spacesAndComments', [] ],
                                        [ 'name', 'mod' ],
                                        [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                        [ 'value', [ 'string', '0-mode' ] ],
                                        [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                        [ 'value', 'v2' ],
                                        [ 'spacesAndComments', [] ] ] ] ],
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                      [ 'name', 'tag' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [] ],
                                  [ 'literalBody', [ 'string', '\'', [ 'a' ] ] ],
                                  [ 'spacesAndComments',
                                    [ [ 'spaces', '  ' ],
                                      [ 'comment', '//  mod 0-mode v2, tag:\'a\'' ] ] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'sub',
                              [ [ 'spacesAndComments', [ [ 'spaces', '\n  ' ] ] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'mix' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'literalBody',
                                    [ 'arr',
                                      [ 'commaList',
                                        [ 'arrItem',
                                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                          [ 'obj',
                                            [ 'commaList',
                                              [ 'objItem',
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                [ 'name', 'elemMods' ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                [ 'obj',
                                                  [ 'commaList',
                                                    [ 'objItem',
                                                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                      [ 'name', 'm2' ],
                                                      [ 'spacesAndComments', [] ],
                                                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                                      [ 'string', '\'', [ 'v', '2' ] ],
                                                      [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ],
                                                [ 'spacesAndComments', [] ] ] ] ],
                                          [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                                  [ 'spacesAndComments', [ [ 'spaces', '  ' ] ] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'sub',
                              [ [ 'spacesAndComments', [] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'js' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'literalBody', [ 'bool', 'true' ] ],
                                  [ 'spacesAndComments', [] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'spacesAndComments', [] ] ] ],
                        [ 'spacesAndComments', [] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ]
               );
    });

    it('should parse before and after comments', function () {
      testParse('./kparser/before-after-comments.bemhtml',
                [ 'stmts',
                  [ 'stmt',
                    [ 'spacesAndComments', [] ],
                    [ 'template',
                      [ [ 'spacesAndComments', [] ],
                        [ 'predicates',
                          [ 'pred',
                            [ 'block',
                              [ [ 'spacesAndComments', [] ],
                                [ 'name', 'block' ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                [ 'value', [ 'string', 'logo' ] ],
                                [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ] ] ] ],
                        [ 'spacesAndComments', [] ],
                        [ 'templateBlock',
                          [ [ 'sub',
                              [ [ 'spacesAndComments',
                                  [ [ 'spaces', '\n  ' ],
                                    [ 'comment', '// before comment' ],
                                    [ 'spaces', '\n  ' ] ] ],
                                [ 'predicates',
                                  [ 'pred',
                                    [ 'stdMode',
                                      [ 'spacesAndComments', [] ],
                                      [ 'name', 'tag' ],
                                      [ 'spacesAndComments', [] ] ] ] ],
                                [ 'spacesAndComments', [] ],
                                [ 'body',
                                  [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                  [ 'generalBody',
                                    [ 'stmt',
                                      [ 'spacesAndComments', [] ],
                                      [ 'blockStmt',
                                        [ 'stmts',
                                          [ 'stmt',
                                            [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                            [ 'returnStmt',
                                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ],
                                              [ 'getExprDot',
                                                [ 'getExprDot',
                                                  [ 'keyword', 'this' ],
                                                  [ 'spacesAndComments', [] ],
                                                  [ 'spacesAndComments', [] ],
                                                  [ 'name', 'ctx' ] ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'spacesAndComments', [] ],
                                                [ 'name', 'bla' ] ],
                                              [ 'spacesAndComments', [ [ 'spaces', ' ' ] ] ] ],
                                            [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                                            [ 'spacesAndComments', [] ] ] ] ],
                                      [ 'stmtEnd' ],
                                      [ 'spacesAndComments', [] ] ] ],
                                  [ 'spacesAndComments', [] ] ],
                                [ 'spacesAndComments', [] ] ] ],
                            [ 'spacesAndComments',
                              [ [ 'spaces', '\n  ' ],
                                [ 'comment', '// end of template comment' ],
                                [ 'spaces', '\n' ] ] ] ] ],
                        [ 'spacesAndComments', [ [ 'spaces', '\n' ] ] ] ] ],
                    [ 'stmtEnd', [ 'spacesAndComments', [] ] ],
                    [ 'spacesAndComments', [] ] ] ]);
    });

  });

  describe.skip('Compiler', function () {
    testDir('basic', testCompile);
  });

});
